### ISSUE TITLE
sslv3 alert handshake failure

### ISSUE THREAD

**Issue by ads1018** [graphcool/api#13]
I'm using apollo-client and graph.cool. When attempting to pass in the request headers to graph.cool via apollo's [`createNetworkInterface`](http://dev.apollodata.com/core/network.html#createNetworkInterface) method I'm throw an ssl error:

```
500
Internal Server Error.
Error: Network error: request to https://api.graph.cool/simple/v1/cixmkt2ul01q00122mksg82pn failed, reason: write EPROTO 140736952869824:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:769:
Error
    at new ApolloError (/Users/ads1018/Sites/next-apollo-example/node_modules/apollo-client/src/errors/ApolloError.js:29:23)
    at /Users/ads1018/Sites/next-apollo-example/node_modules/apollo-client/src/core/QueryManager.js:143:39
    at /Users/ads1018/Sites/next-apollo-example/node_modules/apollo-client/src/core/QueryManager.js:640:25
    at Array.forEach (native)
    at /Users/ads1018/Sites/next-apollo-example/node_modules/apollo-client/src/core/QueryManager.js:637:27
    at Array.forEach (native)
    at QueryManager.broadcastQueries (/Users/ads1018/Sites/next-apollo-example/node_modules/apollo-client/src/core/QueryManager.js:634:42)
    at QueryManager.broadcastNewStore (/Users/ads1018/Sites/next-apollo-example/node_modules/apollo-client/src/core/QueryManager.js:63:14)
    at /Users/ads1018/Sites/next-apollo-example/node_modules/apollo-client/src/ApolloClient.js:30:44
    at Object.dispatch (/Users/ads1018/Sites/next-apollo-example/node_modules/redux/lib/applyMiddleware.js:45:18)
```
It seems like graph.cool doesn't like when I pass request headers for some reason. It works perfectly fine when I don't pass them. Could someone clarify this issue?

**Comment by marktani** [comment]
Hey @ads1018! Thanks for the report. I'm moving it to our [console project](https://github.com/graphcool/console/issues/610)
